export const ProfilePageData = [
    {
        id: 1,
        name: "Aarav Kapoor",
        username: "aarav.codes",
        profileImg: "https://randomuser.me/api/portraits/men/75.jpg",
        coverImg: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?q=80&w=1600",
        followers: 2800,
        following: 1500,
        livesIn: "Bangalore, India",
        from: "India",
        intro: "Building dreams with code 💻☕",
    },
    {
        id: 2,
        name: "Sophia Bennett",
        username: "sophia_bennett",
        profileImg: "https://randomuser.me/api/portraits/women/44.jpg",
        coverImg: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1600",
        followers: 5200,
        following: 980,
        livesIn: "London, United Kingdom",
        from: "United Kingdom",
        intro: "Exploring art, fashion & stories 🎨✨",
    },
    {
        id: 3,
        name: "Rohan Mehta",
        username: "rohan.me",
        profileImg: "https://randomuser.me/api/portraits/men/56.jpg",
        coverImg: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600",
        followers: 3400,
        following: 2100,
        livesIn: "Toronto, Canada",
        from: "Canada",
        intro: "Tech nerd with a travel soul 🌍💡",
    },
    {
        id: 4,
        name: "Emily Carter",
        username: "emilycarter_",
        profileImg: "https://randomuser.me/api/portraits/women/15.jpg",
        coverImg: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1600",
        followers: 7800,
        following: 430,
        livesIn: "New York, United States",
        from: "United States",
        intro: "Lifestyle blogger | Coffee addict ☕📸",
    },
    {
        id: 5,
        name: "Kabir Singh",
        username: "kabir_vibes",
        profileImg: "https://randomuser.me/api/portraits/men/19.jpg",
        coverImg: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?q=80&w=1600",
        followers: 1800,
        following: 600,
        livesIn: "Delhi, India",
        from: "India",
        intro: "Chasing sunsets and success 🌅💼",
    },
    {
        id: 6,
        name: "Hannah Lee",
        username: "hanlee_art",
        profileImg: "https://randomuser.me/api/portraits/women/31.jpg",
        coverImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600",
        followers: 6700,
        following: 1300,
        livesIn: "Seoul, South Korea",
        from: "South Korea",
        intro: "Minimalist artist & dream chaser 🎨🌸",
    },
    {
        id: 7,
        name: "Lucas Martinez",
        username: "lucas.designs",
        profileImg: "https://randomuser.me/api/portraits/men/50.jpg",
        coverImg: "https://images.unsplash.com/photo-1499346030926-9a72daac6c63?q=80&w=1600",
        followers: 4200,
        following: 1700,
        livesIn: "Barcelona, Spain",
        from: "Spain",
        intro: "UX Designer | Traveler | Food lover 🍕🛫",
    },
    {
        id: 8,
        name: "Aisha Khan",
        username: "aisha.k",
        profileImg: "https://randomuser.me/api/portraits/women/48.jpg",
        coverImg: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1600",
        followers: 3900,
        following: 2100,
        livesIn: "Dubai, UAE",
        from: "UAE",
        intro: "Empowered. Elegant. Evolving 💫",
    },
    {
        id: 9,
        name: "Ethan Parker",
        username: "ethan.codes",
        profileImg: "https://randomuser.me/api/portraits/men/22.jpg",
        coverImg: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=1600",
        followers: 3100,
        following: 1250,
        livesIn: "San Francisco, United States",
        from: "United States",
        intro: "Full Stack Dev | Building cool stuff 🚀",
    },
    {
        id: 10,
        name: "Mia Fernandes",
        username: "mia.f_",
        profileImg: "https://randomuser.me/api/portraits/women/85.jpg",
        coverImg: "https://images.unsplash.com/photo-1520974735194-6a2a3beab6c3?q=80&w=1600",
        followers: 9100,
        following: 880,
        livesIn: "Lisbon, Portugal",
        from: "Portugal",
        intro: "Dreamer | Dancer | Designer 🌈💃",
    },
    {
        id: 11,
        name: "Arjun Desai",
        username: "arjun.d",
        profileImg: "https://randomuser.me/api/portraits/men/46.jpg",
        coverImg: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600",
        followers: 2500,
        following: 960,
        livesIn: "Singapore",
        from: "India",
        intro: "Entrepreneur mindset ⚙️🌏",
    },
    {
        id: 12,
        name: "Isabella Rossi",
        username: "bella_rossi",
        profileImg: "https://randomuser.me/api/portraits/women/79.jpg",
        coverImg: "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1600",
        followers: 7400,
        following: 540,
        livesIn: "Milan, Italy",
        from: "Italy",
        intro: "Fashion | Beauty | Confidence 💋",
    },
    {
        id: 13,
        name: "Karan Malhotra",
        username: "karan.ml",
        profileImg: "https://randomuser.me/api/portraits/men/28.jpg",
        coverImg: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600",
        followers: 1800,
        following: 800,
        livesIn: "Sydney, Australia",
        from: "Australia",
        intro: "Coding. Gym. Chill. Repeat 🔥",
    },
    {
        id: 14,
        name: "Zara Patel",
        username: "zara.world",
        profileImg: "https://randomuser.me/api/portraits/women/54.jpg",
        coverImg: "https://images.unsplash.com/photo-1520975918313-60a7d5e3b9b0?q=80&w=1600",
        followers: 6600,
        following: 1200,
        livesIn: "Mumbai, India",
        from: "India",
        intro: "Storyteller | Influencer | Dreamer 💖",
    },
    {
        id: 15,
        name: "Leo Anders",
        username: "leo.anders",
        profileImg: "https://randomuser.me/api/portraits/men/8.jpg",
        coverImg: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1600",
        followers: 5300,
        following: 2200,
        livesIn: "Stockholm, Sweden",
        from: "Sweden",
        intro: "Photography & tech enthusiast 📷💡",
    },
    {
        id: 16,
        name: "Ananya Roy",
        username: "ananya_r",
        profileImg: "https://randomuser.me/api/portraits/women/92.jpg",
        coverImg: "https://images.unsplash.com/photo-1519985176271-adb1088fa94c?q=80&w=1600",
        followers: 4500,
        following: 900,
        livesIn: "Kolkata, India",
        from: "India",
        intro: "Poet | Designer | Dream in color 🎨",
    },
    {
        id: 17,
        name: "Noah Kim",
        username: "noah.codes",
        profileImg: "https://randomuser.me/api/portraits/men/62.jpg",
        coverImg: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?q=80&w=1600",
        followers: 7200,
        following: 1100,
        livesIn: "Tokyo, Japan",
        from: "Japan",
        intro: "Engineering the future 🚀",
    },
    {
        id: 18,
        name: "Lara D’Souza",
        username: "lara.ds",
        profileImg: "https://randomuser.me/api/portraits/women/38.jpg",
        coverImg: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=1600",
        followers: 3900,
        following: 1800,
        livesIn: "Goa, India",
        from: "India",
        intro: "Sun, sea, and creativity 🌊✨",
    },
    {
        id: 19,
        name: "Evelyn Scott",
        username: "eve_scott",
        profileImg: "https://randomuser.me/api/portraits/women/26.jpg",
        coverImg: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?q=80&w=1600",
        followers: 9400,
        following: 1300,
        livesIn: "Los Angeles, United States",
        from: "United States",
        intro: "Filmmaker & dream believer 🎬🌟",
    },
    {
        id: 20,
        name: "Ritik Sharma",
        username: "ritik_dev",
        profileImg: "https://randomuser.me/api/portraits/men/32.jpg",
        coverImg: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1600",
        followers: 2700,
        following: 1400,
        livesIn: "Berlin, Germany",
        from: "Germany",
        intro: "Frontend developer | Traveler ✈️💻",
    },
    {
        id: 21,
        name: "Vivaan Roy",
        username: "vivaan.roy",
        profileImg: "https://randomuser.me/api/portraits/men/34.jpg",
        coverImg: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600",
        followers: 4600,
        following: 1100,
        livesIn: "Bengaluru, India",
        from: "India",
        intro: "Full‑stack dev | Open‑source enthusiast 🚀",
    },
    {
        id: 22,
        name: "Leila Ahmed",
        username: "leila.a.design",
        profileImg: "https://randomuser.me/api/portraits/women/65.jpg",
        coverImg: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1600",
        followers: 8200,
        following: 400,
        livesIn: "Dubai, UAE",
        from: "UAE",
        intro: "Product Designer | Simplifying experiences ✨",
    },
    {
        id: 23,
        name: "Mateo González",
        username: "mateo.g.dev",
        profileImg: "https://randomuser.me/api/portraits/men/71.jpg",
        coverImg: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1600",
        followers: 3500,
        following: 2100,
        livesIn: "Madrid, Spain",
        from: "Spain",
        intro: "Code. Travel. Photograph. 📷✈️",
    },
    {
        id: 24,
        name: "Yuna Kim",
        username: "yuna.k.creative",
        profileImg: "https://randomuser.me/api/portraits/women/22.jpg",
        coverImg: "https://images.unsplash.com/photo-1505944353524-3ecfce17c5e9?q=80&w=1600",
        followers: 9100,
        following: 780,
        livesIn: "Seoul, South Korea",
        from: "South Korea",
        intro: "Motion graphics artist | Lover of flow 🎬",
    },
    {
        id: 25,
        name: "Artem Ivanov",
        username: "artem.ivanov.tech",
        profileImg: "https://randomuser.me/api/portraits/men/49.jpg",
        coverImg: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1600",
        followers: 4200,
        following: 1500,
        livesIn: "Moscow, Russia",
        from: "Russia",
        intro: "Backend engineer | Building scalable systems ⚙️",
    },
    {
        id: 26,
        name: "Nia Johnson",
        username: "nia.johnson.writer",
        profileImg: "https://randomuser.me/api/portraits/women/14.jpg",
        coverImg: "https://images.unsplash.com/photo-1483721310020-03333e577078?q=80&w=1600",
        followers: 6700,
        following: 1400,
        livesIn: "Chicago, United States",
        from: "United States",
        intro: "Storyteller | Content strategist 📝",
    },
    {
        id: 27,
        name: "Diego Silva",
        username: "diego.silva.photo",
        profileImg: "https://randomuser.me/api/portraits/men/55.jpg",
        coverImg: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600",
        followers: 5600,
        following: 900,
        livesIn: "Rio de Janeiro, Brazil",
        from: "Brazil",
        intro: "Capturing moments one frame at a time 📸",
    },
    {
        id: 28,
        name: "Amara Njeri",
        username: "amara.njeri",
        profileImg: "https://randomuser.me/api/portraits/women/35.jpg",
        coverImg: "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1600",
        followers: 3100,
        following: 1800,
        livesIn: "Nairobi, Kenya",
        from: "Kenya",
        intro: "Tech educator | Empowering youth globally 🌍",
    },
    {
        id: 29,
        name: "Hugo Martins",
        username: "hugo.m.design",
        profileImg: "https://randomuser.me/api/portraits/men/82.jpg",
        coverImg: "https://images.unsplash.com/photo-1519985176271-adb1088fa94c?q=80&w=1600",
        followers: 7900,
        following: 500,
        livesIn: "Lisbon, Portugal",
        from: "Portugal",
        intro: "UX & UI designer | Making interfaces alive 🎨",
    },
    {
        id: 30,
        name: "Priya Menon",
        username: "priya.menon.dev",
        profileImg: "https://randomuser.me/api/portraits/women/73.jpg",
        coverImg: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600",
        followers: 2400,
        following: 950,
        livesIn: "Kochi, India",
        from: "India",
        intro: "Frontend developer | React & TypeScript 💻",
    },
    {
        id: 31,
        name: "Omar Al‑Hassan",
        username: "omar.has.dev",
        profileImg: "https://randomuser.me/api/portraits/men/60.jpg",
        coverImg: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1600",
        followers: 6300,
        following: 1200,
        livesIn: "Abu Dhabi, UAE",
        from: "UAE",
        intro: "Cloud engineer | Serverless fan ☁️",
    },
    {
        id: 32,
        name: "Sophie Laurent",
        username: "sophie.l.design",
        profileImg: "https://randomuser.me/api/portraits/women/21.jpg",
        coverImg: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?q=80&w=1600",
        followers: 8800,
        following: 430,
        livesIn: "Paris, France",
        from: "France",
        intro: "Fashion tech | Bridging style & code 👗💻",
    },
    {
        id: 33,
        name: "Zheng Wei",
        username: "zheng.wei.engineer",
        profileImg: "https://randomuser.me/api/portraits/men/68.jpg",
        coverImg: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=1600",
        followers: 4700,
        following: 1700,
        livesIn: "Beijing, China",
        from: "China",
        intro: "AI engineer | Data & Deep Learning 🧠",
    },
    {
        id: 34,
        name: "Maria Petrova",
        username: "maria.petrova.art",
        profileImg: "https://randomuser.me/api/portraits/women/18.jpg",
        coverImg: "https://images.unsplash.com/photo-1519985176271-adb1088fa94c?q=80&w=1600",
        followers: 5400,
        following: 880,
        livesIn: "Sofia, Bulgaria",
        from: "Bulgaria",
        intro: "Digital artist | Expression through color 🎨",
    },
    {
        id: 35,
        name: "Jayden Brown",
        username: "jayden.brown.dev",
        profileImg: "https://randomuser.me/api/portraits/men/13.jpg",
        coverImg: "https://images.unsplash.com/photo-1520974735194-6a2a3beab6c3?q=80&w=1600",
        followers: 6700,
        following: 1300,
        livesIn: "Toronto, Canada",
        from: "Canada",
        intro: "Full‑stack developer | Coffee + Code ☕💻",
    },
    {
        id: 36,
        name: "Kiara Rossi",
        username: "kiara.rossi.creative",
        profileImg: "https://randomuser.me/api/portraits/women/30.jpg",
        coverImg: "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1600",
        followers: 3200,
        following: 1500,
        livesIn: "Rome, Italy",
        from: "Italy",
        intro: "Brand strategist | Visual storyteller 📊",
    },
    {
        id: 37,
        name: "Samir Patel",
        username: "samir.patel.tech",
        profileImg: "https://randomuser.me/api/portraits/men/37.jpg",
        coverImg: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1600",
        followers: 2900,
        following: 1400,
        livesIn: "Ahmedabad, India",
        from: "India",
        intro: "Mobile dev | Android & React Native 🔧",
    },
    {
        id: 38,
        name: "Elena Novak",
        username: "elena.novak.photography",
        profileImg: "https://randomuser.me/api/portraits/women/42.jpg",
        coverImg: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600",
        followers: 8600,
        following: 650,
        livesIn: "Vienna, Austria",
        from: "Austria",
        intro: "Fine‑art photographer | Light & shadow lover 📷",
    },
    {
        id: 39,
        name: "Takeshi Yamamoto",
        username: "takeshi.y.dev",
        profileImg: "https://randomuser.me/api/portraits/men/66.jpg",
        coverImg: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1600",
        followers: 4100,
        following: 1250,
        livesIn: "Tokyo, Japan",
        from: "Japan",
        intro: "DevOps engineer | Automation advocate 🔁",
    },
    {
        id: 40,
        name: "Chloe Martin",
        username: "chloe.martin.writer",
        profileImg: "https://randomuser.me/api/portraits/women/17.jpg",
        coverImg: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1600",
        followers: 9200,
        following: 850,
        livesIn: "Melbourne, Australia",
        from: "Australia",
        intro: "Content creator | Travel & lifestyle 🌿✈️",
    },
    {
        id: 41,
        name: "Ibrahim Al Farsi",
        username: "ibrahim.farsi",
        profileImg: "https://randomuser.me/api/portraits/men/53.jpg",
        coverImg: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=1600",
        followers: 3700,
        following: 1900,
        livesIn: "Muscat, Oman",
        from: "Oman",
        intro: "Cybersecurity analyst | Protecting the digital world 🛡️",
    },
    {
        id: 42,
        name: "Nadia Petrov",
        username: "nadia.petrov.design",
        profileImg: "https://randomuser.me/api/portraits/women/59.jpg",
        coverImg: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600",
        followers: 7600,
        following: 560,
        livesIn: "Prague, Czech Republic",
        from: "Czech Republic",
        intro: "UI/UX designer | Human‑centred design ❤️",
    },
    {
        id: 43,
        name: "Ravi Kumar",
        username: "ravi.kumar.ai",
        profileImg: "https://randomuser.me/api/portraits/men/44.jpg",
        coverImg: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?q=80&w=1600",
        followers: 2800,
        following: 1020,
        livesIn: "Hyderabad, India",
        from: "India",
        intro: "Machine‑learning engineer | Data enthusiast 📊",
    },
    {
        id: 44,
        name: "Olivia Svensson",
        username: "olivia.svensson",
        profileImg: "https://randomuser.me/api/portraits/women/27.jpg",
        coverImg: "https://images.unsplash.com/photo-1520974735194-6a2a3beab6c3?q=80&w=1600",
        followers: 8400,
        following: 730,
        livesIn: "Stockholm, Sweden",
        from: "Sweden",
        intro: "Photographer & travel blogger 🌍📸",
    },
    {
        id: 45,
        name: "Mateja Novak",
        username: "mateja.novak",
        profileImg: "https://randomuser.me/api/portraits/women/24.jpg",
        coverImg: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1600",
        followers: 4800,
        following: 1550,
        livesIn: "Ljubljana, Slovenia",
        from: "Slovenia",
        intro: "Graphic designer | Crafting meaningful visuals 🎨",
    },
    {
        id: 46,
        name: "Felipe Costa",
        username: "felipe.costa.tech",
        profileImg: "https://randomuser.me/api/portraits/men/21.jpg",
        coverImg: "https://images.unsplash.com/photo-1483721310020-03333e577078?q=80&w=1600",
        followers: 3300,
        following: 1180,
        livesIn: "São Paulo, Brazil",
        from: "Brazil",
        intro: "Mobile engineer | Android & Kotlin 💙",
    },
    {
        id: 47,
        name: "Yara Elbaz",
        username: "yara.elbaz",
        profileImg: "https://randomuser.me/api/portraits/women/40.jpg",
        coverImg: "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1600",
        followers: 7000,
        following: 900,
        livesIn: "Cairo, Egypt",
        from: "Egypt",
        intro: "Digital marketer | Growth hacker 📈",
    },
    {
        id: 48,
        name: "Jinwoo Park",
        username: "jinwoo.park",
        profileImg: "https://randomuser.me/api/portraits/men/58.jpg",
        coverImg: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1600",
        followers: 5900,
        following: 1320,
        livesIn: "Seoul, South Korea",
        from: "South Korea",
        intro: "UX researcher | Human‑centric thinking 🧮",
    },
    {
        id: 49,
        name: "Amelia Thompson",
        username: "amelia.thompson",
        profileImg: "https://randomuser.me/api/portraits/women/69.jpg",
        coverImg: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600",
        followers: 9600,
        following: 610,
        livesIn: "Vancouver, Canada",
        from: "Canada",
        intro: "Entrepreneur | Tech + Sustainability 🌱",
    },
    {
        id: 50,
        name: "Sven Müller",
        username: "sven.mueller.dev",
        profileImg: "https://randomuser.me/api/portraits/men/72.jpg",
        coverImg: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1600",
        followers: 4300,
        following: 1600,
        livesIn: "Berlin, Germany",
        from: "Germany",
        intro: "Frontend engineer | React & Vue enthusiast 🖥️",
    },
    {
        id: 51,
        name: "Lina Gómez",
        username: "lina.gomez.art",
        profileImg: "https://randomuser.me/api/portraits/women/52.jpg",
        coverImg: "https://images.unsplash.com/photo-1519985176271-adb1088fa94c?q=80&w=1600",
        followers: 5500,
        following: 1400,
        livesIn: "Barcelona, Spain",
        from: "Spain",
        intro: "Illustrator | Bringing ideas to life ✏️",
    },
    {
        id: 52,
        name: "Rakesh Singh",
        username: "rakesh.singh.dev",
        profileImg: "https://randomuser.me/api/portraits/men/17.jpg",
        coverImg: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1600",
        followers: 2600,
        following: 1050,
        livesIn: "Pune, India",
        from: "India",
        intro: "Software engineer | Cloud & microservices ☁️",
    },
    {
        id: 53,
        name: "Zoe Wang",
        username: "zoe.wang.design",
        profileImg: "https://randomuser.me/api/portraits/women/66.jpg",
        coverImg: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=1600",
        followers: 7200,
        following: 770,
        livesIn: "Shanghai, China",
        from: "China",
        intro: "Product designer | UX for good 💡",
    },
    {
        id: 54,
        name: "Hassan Al‑Ghamdi",
        username: "hassan.ghamdi",
        profileImg: "https://randomuser.me/api/portraits/men/45.jpg",
        coverImg: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1600",
        followers: 3000,
        following: 1400,
        livesIn: "Jeddah, Saudi Arabia",
        from: "Saudi Arabia",
        intro: "Cyber‑physical systems engineer | IoT & edge 🔌",
    },
    {
        id: 55,
        name: "Priyanka Desai",
        username: "priyanka.desai",
        profileImg: "https://randomuser.me/api/portraits/women/34.jpg",
        coverImg: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600",
        followers: 6500,
        following: 930,
        livesIn: "Mumbai, India",
        from: "India",
        intro: "Design lead | Crafting brand stories 📘",
    },
    {
        id: 56,
        name: "Lukas Novak",
        username: "lukas.novak.dev",
        profileImg: "https://randomuser.me/api/portraits/men/38.jpg",
        coverImg: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600",
        followers: 3800,
        following: 1120,
        livesIn: "Prague, Czech Republic",
        from: "Czech Republic",
        intro: "Full‑stack dev | Node & GraphQL ⚡",
    },
    {
        id: 57,
        name: "Isla McKenzie",
        username: "isla.mckenzie",
        profileImg: "https://randomuser.me/api/portraits/women/23.jpg",
        coverImg: "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1600",
        followers: 8000,
        following: 510,
        livesIn: "Edinburgh, United Kingdom",
        from: "United Kingdom",
        intro: "UX researcher | Human‑first design 🧩",
    },
    {
        id: 58,
        name: "Daniel Kim",
        username: "daniel.kim.tech",
        profileImg: "https://randomuser.me/api/portraits/men/30.jpg",
        coverImg: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1600",
        followers: 4700,
        following: 1650,
        livesIn: "Vancouver, Canada",
        from: "Canada",
        intro: "DevOps & SRE | Reliability matters 🛠️",
    },
    {
        id: 59,
        name: "Mina Youssef",
        username: "mina.youssef",
        profileImg: "https://randomuser.me/api/portraits/women/41.jpg",
        coverImg: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600",
        followers: 5900,
        following: 910,
        livesIn: "Cairo, Egypt",
        from: "Egypt",
        intro: "Data scientist | Turning data into decisions 📈",
    },
    {
        id: 60,
        name: "Felix Müller",
        username: "felix.mueller.design",
        profileImg: "https://randomuser.me/api/portraits/men/64.jpg",
        coverImg: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1600",
        followers: 5200,
        following: 1370,
        livesIn: "Hamburg, Germany",
        from: "Germany",
        intro: "Motion designer | Visual impact 🎥",
    }
];
